# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_auto_20171116_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='foodmoney',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='金额'),
        ),
    ]
