# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0003_auto_20171116_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecord',
            name='foodcnt',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
    ]
