# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0007_auto_20171119_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipindex', models.CharField(max_length=20, unique=True, verbose_name='用户编号')),
                ('vipname', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('vipnumber', models.CharField(max_length=15, verbose_name='用户电话')),
                ('vipcnt', models.PositiveIntegerField(default=32, verbose_name='月卡牛奶数量')),
            ],
        ),
        migrations.CreateModel(
            name='VIPRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viprecordcnt', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('viprecordtime', models.DateTimeField(verbose_name='时间')),
                ('viprecordname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.VIPInfo')),
            ],
        ),
        migrations.CreateModel(
            name='VIPType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viptype', models.CharField(max_length=30, unique=True, verbose_name='月卡类型名称')),
            ],
        ),
        migrations.AddField(
            model_name='vipinfo',
            name='viptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.VIPType'),
        ),
    ]
